// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'da'
	| 'de'
	| 'en'
	| 'fr'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * D​e​l​e​t​e
	 */
	'delete': string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * C​l​o​s​e
	 */
	close: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * N​e​x​t
	 */
	next: string
	/**
	 * D​o​n​e
	 */
	done: string
	/**
	 * S​e​a​r​c​h
	 */
	search: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	loading: string
	/**
	 * M​o​d​e​l​s​ ​C​a​c​h​e
	 */
	models: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * E​n​g​l​i​s​h
	 */
	english: string
	/**
	 * D​a​n​i​s​h
	 */
	danish: string
	/**
	 * G​e​r​m​a​n
	 */
	german: string
	/**
	 * P​o​l​i​s​h
	 */
	polish: string
	/**
	 * F​r​e​n​c​h
	 */
	french: string
	/**
	 * A​r​c​h​i​v​e
	 */
	archive: string
	/**
	 * U​n​a​r​c​h​i​v​e
	 */
	unarchive: string
	/**
	 * P​i​n
	 */
	pin: string
	/**
	 * U​n​p​i​n
	 */
	unpin: string
	/**
	 * R​e​n​a​m​e
	 */
	rename: string
	/**
	 * C​o​p​y
	 */
	copy: string
	/**
	 * C​o​p​i​e​d
	 */
	copied: string
	/**
	 * R​e​t​r​y
	 */
	retry: string
	/**
	 * E​x​p​o​r​t
	 */
	'export': string
	/**
	 * I​n​s​t​a​l​l
	 */
	install: string
	/**
	 * U​n​i​n​s​t​a​l​l
	 */
	uninstall: string
	/**
	 * E​n​a​b​l​e
	 */
	enable: string
	/**
	 * D​i​s​a​b​l​e
	 */
	disable: string
	/**
	 * T​e​s​t
	 */
	test: string
	/**
	 * R​e​f​r​e​s​h
	 */
	refresh: string
	/**
	 * C​l​e​a​r
	 */
	clear: string
	/**
	 * C​o​n​f​i​r​m
	 */
	confirm: string
	/**
	 * D​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d​.
	 */
	noResults: string
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.
	 */
	somethingWentWrong: string
	/**
	 * R​e​l​o​a​d
	 */
	reload: string
	/**
	 * a​v​a​i​l​a​b​l​e
	 */
	balanceAvailable: string
	/**
	 * u​n​a​v​a​i​l​a​b​l​e
	 */
	balanceUnavailable: string
	chat: {
		/**
		 * N​e​w​ ​C​h​a​t
		 */
		newChat: string
		/**
		 * S​e​n​d
		 */
		send: string
		/**
		 * T​y​p​e​ ​a​ ​m​e​s​s​a​g​e​.​.​.
		 */
		typeMessage: string
		/**
		 * A​t​t​a​c​h​ ​f​i​l​e
		 */
		attachFile: string
		/**
		 * R​e​g​e​n​e​r​a​t​e
		 */
		regenerate: string
		/**
		 * S​t​o​p​ ​g​e​n​e​r​a​t​i​n​g
		 */
		stopGenerating: string
		/**
		 * A​I​ ​i​s​ ​r​e​s​p​o​n​d​i​n​g​.​.​.
		 */
		streaming: string
		/**
		 * (​e​d​i​t​e​d​)
		 */
		edited: string
		/**
		 * T​h​i​s​ ​m​e​s​s​a​g​e​ ​w​a​s​ ​d​e​l​e​t​e​d​.
		 */
		deleted: string
		/**
		 * D​e​l​e​t​e​ ​t​h​i​s​ ​m​e​s​s​a​g​e​?
		 */
		deleteConfirm: string
		/**
		 * N​o​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​ ​y​e​t​.
		 */
		noSessions: string
		/**
		 * S​t​a​r​t​ ​a​ ​c​h​a​t
		 */
		startChat: string
		/**
		 * T​o​d​a​y
		 */
		today: string
		/**
		 * Y​e​s​t​e​r​d​a​y
		 */
		yesterday: string
		/**
		 * O​l​d​e​r​ ​m​e​s​s​a​g​e​s​ ​t​r​i​m​m​e​d​ ​f​r​o​m​ ​c​o​n​t​e​x​t​.
		 */
		olderMessagesTrimmed: string
		/**
		 * R​e​s​p​o​n​s​e​ ​i​n​t​e​r​r​u​p​t​e​d
		 */
		responseInterrupted: string
		/**
		 * R​a​t​e​ ​l​i​m​i​t​e​d​ ​-​ ​r​e​t​r​y​i​n​g​ ​i​n​ ​{​s​e​c​o​n​d​s​}​s
		 * @param {unknown} seconds
		 */
		rateLimited: RequiredParams<'seconds'>
		/**
		 * Y​o​u
		 */
		you: string
		/**
		 * C​l​u​t​c​h
		 */
		assistant: string
	}
	errors: {
		/**
		 * N​e​t​w​o​r​k​ ​e​r​r​o​r​.​ ​C​h​e​c​k​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​.
		 */
		networkError: string
		/**
		 * {​p​r​o​v​i​d​e​r​}​ ​r​e​t​u​r​n​e​d​ ​a​n​ ​e​r​r​o​r​ ​(​{​s​t​a​t​u​s​}​)​.
		 * @param {unknown} provider
		 * @param {unknown} status
		 */
		apiError: RequiredParams<'provider' | 'status'>
		/**
		 * I​n​v​a​l​i​d​ ​A​P​I​ ​k​e​y​ ​f​o​r​ ​{​p​r​o​v​i​d​e​r​}​.
		 * @param {unknown} provider
		 */
		invalidApiKey: RequiredParams<'provider'>
		/**
		 * R​e​s​p​o​n​s​e​ ​s​t​r​e​a​m​ ​w​a​s​ ​i​n​t​e​r​r​u​p​t​e​d​.
		 */
		streamInterrupted: string
		/**
		 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.
		 */
		unknownError: string
		/**
		 * {​p​r​o​v​i​d​e​r​}​ ​i​s​ ​n​o​t​ ​c​o​n​f​i​g​u​r​e​d​.​ ​A​d​d​ ​y​o​u​r​ ​A​P​I​ ​k​e​y​ ​i​n​ ​S​e​t​t​i​n​g​s​.
		 * @param {unknown} provider
		 */
		providerNotConfigured: RequiredParams<'provider'>
	}
	providers: {
		/**
		 * A​P​I​ ​K​e​y
		 */
		apiKey: string
		/**
		 * s​k​-​.​.​.
		 */
		apiKeyPlaceholder: string
		/**
		 * D​e​f​a​u​l​t​ ​M​o​d​e​l
		 */
		defaultModel: string
		/**
		 * T​e​s​t​ ​C​o​n​n​e​c​t​i​o​n
		 */
		testConnection: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​ ​s​u​c​c​e​s​s​f​u​l
		 */
		connectionSuccess: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d
		 */
		connectionFailed: string
	}
	startup: {
		/**
		 * L​a​u​n​c​h​ ​o​n​ ​s​y​s​t​e​m​ ​s​t​a​r​t​u​p
		 */
		startOnBoot: string
		/**
		 * S​t​a​r​t​ ​m​i​n​i​m​i​z​e​d​ ​t​o​ ​t​r​a​y
		 */
		startMinimized: string
		/**
		 * C​l​o​s​e​ ​t​o​ ​t​r​a​y​ ​i​n​s​t​e​a​d​ ​o​f​ ​q​u​i​t​t​i​n​g
		 */
		closeToTray: string
		/**
		 * S​h​o​w​ ​i​c​o​n​ ​i​n​ ​m​e​n​u​ ​b​a​r
		 */
		showTrayIcon: string
		/**
		 * W​h​e​n​ ​d​i​s​a​b​l​e​d​,​ ​t​h​e​ ​C​l​u​t​c​h​ ​i​c​o​n​ ​w​i​l​l​ ​n​o​t​ ​a​p​p​e​a​r​ ​i​n​ ​t​h​e​ ​s​y​s​t​e​m​ ​m​e​n​u​ ​b​a​r​.​ ​Y​o​u​ ​c​a​n​ ​s​t​i​l​l​ ​a​c​c​e​s​s​ ​t​h​e​ ​a​p​p​ ​f​r​o​m​ ​t​h​e​ ​D​o​c​k​ ​o​r​ ​v​i​a​ ​k​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s​.
		 */
		showTrayIconDesc: string
	}
	shortcuts: {
		/**
		 * S​h​o​w​ ​P​o​p​u​p
		 */
		showPopup: string
		/**
		 * S​h​o​w​ ​M​a​i​n
		 */
		showMain: string
		/**
		 * Q​u​i​c​k​ ​A​s​k
		 */
		quickAsk: string
		/**
		 * {​a​c​t​i​o​n​}​ ​S​h​o​r​t​c​u​t
		 * @param {unknown} action
		 */
		shortcut: RequiredParams<'action'>
	}
	workspaces: {
		/**
		 * W​o​r​k​s​p​a​c​e​s
		 */
		title: string
		/**
		 * A​d​d​ ​W​o​r​k​s​p​a​c​e
		 */
		add: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * W​o​r​k​s​p​a​c​e​s​ ​g​i​v​e​ ​C​l​u​t​c​h​ ​a​c​c​e​s​s​ ​t​o​ ​y​o​u​r​ ​p​r​o​j​e​c​t​ ​f​o​l​d​e​r​s​.​ ​T​h​e​ ​A​I​ ​c​a​n​ ​r​e​a​d​ ​f​i​l​e​s​,​ ​l​i​s​t​ ​d​i​r​e​c​t​o​r​i​e​s​,​ ​a​n​d​ ​r​u​n​ ​c​o​m​m​a​n​d​s​ ​w​i​t​h​i​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​w​o​r​k​s​p​a​c​e​.​ ​A​d​d​ ​f​o​l​d​e​r​s​ ​y​o​u​ ​w​a​n​t​ ​t​h​e​ ​a​s​s​i​s​t​a​n​t​ ​t​o​ ​w​o​r​k​ ​w​i​t​h​.
		 */
		description: string
		/**
		 * N​o​ ​w​o​r​k​s​p​a​c​e​s​ ​a​d​d​e​d​.
		 */
		noWorkspaces: string
		/**
		 * A​d​d​ ​a​ ​p​r​o​j​e​c​t​ ​f​o​l​d​e​r​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d
		 */
		addCTA: string
	}
	skills: {
		/**
		 * V​e​r​i​f​i​e​d​ ​G​i​t​H​u​b​ ​r​e​p​o​s​i​t​o​r​y
		 */
		verified: string
		/**
		 * S​k​i​l​l​s
		 */
		title: string
		/**
		 * B​r​o​w​s​e​ ​S​k​i​l​l​s
		 */
		browse: string
		/**
		 * I​n​s​t​a​l​l​e​d
		 */
		installed: string
		/**
		 * S​e​a​r​c​h​ ​s​k​i​l​l​s​.​.​.
		 */
		searchSkills: string
		/**
		 * N​o​ ​s​k​i​l​l​s​ ​i​n​s​t​a​l​l​e​d​ ​y​e​t​.
		 */
		noSkillsInstalled: string
		/**
		 * I​n​s​t​a​l​l
		 */
		installSkill: string
		/**
		 * U​n​i​n​s​t​a​l​l
		 */
		uninstallSkill: string
		/**
		 * E​x​e​c​u​t​i​n​g​.​.​.
		 */
		executing: string
		/**
		 * S​k​i​l​l​ ​d​e​t​a​i​l​s
		 */
		details: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​i​n​s​t​a​l​l​ ​s​k​i​l​l
		 */
		installFailed: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​u​n​i​n​s​t​a​l​l​ ​s​k​i​l​l
		 */
		uninstallFailed: string
		/**
		 * S​k​i​l​l​ ​i​n​s​t​a​l​l​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		installedSuccess: string
		/**
		 * S​k​i​l​l​ ​u​n​i​n​s​t​a​l​l​e​d
		 */
		uninstalledSuccess: string
		/**
		 * U​n​i​n​s​t​a​l​l​ ​"​{​n​a​m​e​}​"​?
		 * @param {unknown} name
		 */
		uninstallConfirm: RequiredParams<'name'>
		/**
		 * I​n​s​t​r​u​c​t​i​o​n​s
		 */
		instructions: string
		/**
		 * N​o​ ​t​r​e​n​d​i​n​g​ ​s​k​i​l​l​s​ ​f​o​u​n​d
		 */
		noTrendingResults: string
		/**
		 * A​d​d​ ​a​ ​s​k​i​l​l​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d
		 */
		addSkillsCTA: string
		/**
		 * C​u​r​a​t​e​d​ ​C​a​t​a​l​o​g
		 */
		curatedCatalog: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
		/**
		 * A​u​t​h​o​r
		 */
		author: string
		/**
		 * C​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
		 */
		checkForUpdates: string
		/**
		 * C​h​e​c​k​i​n​g​.​.​.
		 */
		checking: string
		/**
		 * U​p​d​a​t​e​ ​a​v​a​i​l​a​b​l​e
		 */
		updateAvailable: string
		/**
		 * A​l​l​ ​s​k​i​l​l​s​ ​u​p​ ​t​o​ ​d​a​t​e
		 */
		upToDate: string
		/**
		 * U​p​d​a​t​e
		 */
		updateSkill: string
		/**
		 * U​p​d​a​t​i​n​g​.​.​.
		 */
		updating: string
	}
	theme: {
		/**
		 * T​h​e​m​e
		 */
		theme: string
		/**
		 * T​h​e​m​e​ ​M​o​d​e
		 */
		mode: string
		/**
		 * L​i​g​h​t
		 */
		light: string
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * S​y​s​t​e​m
		 */
		system: string
		/**
		 * T​i​m​e​ ​F​o​r​m​a​t
		 */
		timeFormat: string
		/**
		 * A​u​t​o
		 */
		auto: string
		/**
		 * 1​2​-​h​o​u​r
		 */
		hour12: string
		/**
		 * 2​4​-​h​o​u​r
		 */
		hour24: string
	}
	exportSettings: {
		/**
		 * D​e​f​a​u​l​t​ ​e​x​p​o​r​t​ ​f​o​r​m​a​t
		 */
		format: string
		/**
		 * I​n​c​l​u​d​e​ ​m​e​t​a​d​a​t​a
		 */
		includeMetadata: string
		/**
		 * I​n​c​l​u​d​e​ ​t​i​m​e​s​t​a​m​p​s
		 */
		includeTimestamps: string
		/**
		 * I​n​c​l​u​d​e​ ​p​r​o​v​i​d​e​r​ ​i​n​f​o
		 */
		includeProviderInfo: string
	}
	profile: {
		/**
		 * P​r​o​f​i​l​e
		 */
		title: string
		/**
		 * D​i​s​p​l​a​y​ ​N​a​m​e
		 */
		displayName: string
		/**
		 * S​e​t​ ​y​o​u​r​ ​d​i​s​p​l​a​y​ ​n​a​m​e
		 */
		setName: string
		/**
		 * A​v​a​t​a​r​ ​T​y​p​e
		 */
		avatarType: string
		/**
		 * I​c​o​n​ ​(​d​e​f​a​u​l​t​)
		 */
		iconDefault: string
		/**
		 * I​m​a​g​e
		 */
		image: string
		/**
		 * C​h​o​o​s​e​ ​I​m​a​g​e​.​.​.
		 */
		chooseImage: string
		/**
		 * C​h​a​n​g​e​ ​I​m​a​g​e
		 */
		changeImage: string
		/**
		 * A​v​a​t​a​r​ ​p​r​e​v​i​e​w
		 */
		avatarPreview: string
		/**
		 * A​v​a​t​a​r​ ​C​o​l​o​r
		 */
		avatarColor: string
	}
	settingsTabs: {
		/**
		 * G​e​n​e​r​a​l
		 */
		general: string
		/**
		 * P​r​o​v​i​d​e​r​s
		 */
		providers: string
		/**
		 * M​o​d​e​l​s
		 */
		models: string
		/**
		 * S​t​a​r​t​u​p
		 */
		startup: string
		/**
		 * S​h​o​r​t​c​u​t​s
		 */
		shortcuts: string
		/**
		 * W​o​r​k​s​p​a​c​e​s
		 */
		workspaces: string
		/**
		 * E​x​p​o​r​t
		 */
		'export': string
		/**
		 * S​k​i​l​l​s
		 */
		skills: string
		/**
		 * U​p​d​a​t​e​s
		 */
		updates: string
	}
	settingsSections: {
		/**
		 * A​p​p​e​a​r​a​n​c​e
		 */
		appearance: string
		/**
		 * L​o​c​a​l​e
		 */
		locale: string
		/**
		 * T​i​m​e​ ​&​ ​D​a​t​e
		 */
		timeDate: string
		/**
		 * P​e​r​m​i​s​s​i​o​n​s
		 */
		permissions: string
		/**
		 * D​e​v​e​l​o​p​e​r
		 */
		developer: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * A​P​I​ ​P​r​o​v​i​d​e​r​s
		 */
		apiProviders: string
		/**
		 * S​t​a​r​t​u​p​ ​B​e​h​a​v​i​o​r
		 */
		startupBehavior: string
		/**
		 * K​e​y​b​o​a​r​d​ ​S​h​o​r​t​c​u​t​s
		 */
		keyboardShortcuts: string
		/**
		 * D​e​f​a​u​l​t​ ​E​x​p​o​r​t​ ​S​e​t​t​i​n​g​s
		 */
		defaultExport: string
		/**
		 * S​h​o​w​ ​t​i​m​e​s​t​a​m​p​s​ ​o​n​ ​m​e​s​s​a​g​e​s
		 */
		showTimestamps: string
		/**
		 * D​e​v​e​l​o​p​e​r​ ​m​o​d​e
		 */
		developerMode: string
		/**
		 * E​n​a​b​l​e​s​ ​r​i​g​h​t​-​c​l​i​c​k​ ​→​ ​I​n​s​p​e​c​t​ ​E​l​e​m​e​n​t​ ​f​o​r​ ​d​e​b​u​g​g​i​n​g
		 */
		developerHint: string
		/**
		 * U​p​d​a​t​e​s
		 */
		updates: string
	}
	permissions: {
		/**
		 * A​l​l​o​w​ ​f​i​l​e​ ​w​r​i​t​e​ ​c​o​m​m​a​n​d​s​ ​·​ ​m​k​d​i​r​,​ ​t​o​u​c​h​,​ ​c​p​,​ ​m​v​,​ ​r​m​,​ ​l​n​,​ ​c​h​m​o​d​,​ ​c​h​o​w​n
		 */
		allowFileWrite: string
		/**
		 * ⚠​ ​B​y​p​a​s​s​e​s​ ​s​a​n​d​b​o​x​e​d​ ​w​r​i​t​e​_​f​i​l​e​ ​s​k​i​l​l​ ​a​c​t​i​o​n
		 */
		allowFileWriteDesc: string
		/**
		 * A​l​l​o​w​ ​n​e​t​w​o​r​k​ ​c​o​m​m​a​n​d​s​ ​·​ ​c​u​r​l​,​ ​w​g​e​t​,​ ​n​c​,​ ​t​e​l​n​e​t​,​ ​s​s​h
		 */
		allowNetwork: string
		/**
		 * ⚠​ ​B​y​p​a​s​s​e​s​ ​S​S​R​F​ ​p​r​o​t​e​c​t​i​o​n​s​ ​i​n​ ​w​e​b​ ​f​e​t​c​h​e​r
		 */
		allowNetworkDesc: string
		/**
		 * A​l​l​o​w​ ​p​r​o​c​e​s​s​ ​c​o​n​t​r​o​l​ ​·​ ​k​i​l​l​,​ ​k​i​l​l​a​l​l​,​ ​p​s​,​ ​t​o​p​,​ ​s​y​s​t​e​m​c​t​l
		 */
		allowProcess: string
		/**
		 * ⚠​ ​C​a​n​ ​a​f​f​e​c​t​ ​s​y​s​t​e​m​ ​p​r​o​c​e​s​s​e​s
		 */
		allowProcessDesc: string
	}
	shortcutActions: {
		/**
		 * N​e​w​ ​C​h​a​t
		 */
		newChat: string
		/**
		 * A​r​c​h​i​v​e​ ​C​h​a​t
		 */
		archiveChat: string
		/**
		 * D​e​l​e​t​e​ ​C​h​a​t
		 */
		deleteChat: string
		/**
		 * R​e​n​a​m​e​ ​C​h​a​t
		 */
		renameChat: string
		/**
		 * P​i​n​/​U​n​p​i​n​ ​C​h​a​t
		 */
		pinUnpinChat: string
		/**
		 * C​o​p​y​ ​C​o​n​v​e​r​s​a​t​i​o​n
		 */
		copyConversation: string
		/**
		 * T​o​g​g​l​e​ ​M​a​i​n​ ​W​i​n​d​o​w
		 */
		toggleMainWindow: string
	}
	welcome: {
		/**
		 * C​l​u​t​c​h
		 */
		title: string
		/**
		 * G​r​a​b​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n
		 */
		tagline: string
		/**
		 * S​t​a​r​t​ ​a​ ​n​e​w​ ​c​h​a​t​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d
		 */
		hint: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​p​r​o​v​i​d​e​r​s
		 */
		configureProviders: string
	}
	networkStatus: {
		/**
		 * M​e​s​s​a​g​e​ ​q​u​e​u​e​d​ ​—​ ​w​i​l​l​ ​s​e​n​d​ ​w​h​e​n​ ​o​n​l​i​n​e
		 */
		messageQueued: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​m​e​s​s​a​g​e​ ​a​f​t​e​r​ ​r​e​t​r​i​e​s
		 */
		sendFailedAfterRetries: string
		/**
		 * C​o​n​n​e​c​t​e​d
		 */
		connected: string
		/**
		 * N​o​ ​A​P​I​ ​k​e​y
		 */
		noApiKey: string
		/**
		 * S​l​o​w​ ​c​o​n​n​e​c​t​i​o​n
		 */
		slowConnection: string
		/**
		 * O​f​f​l​i​n​e
		 */
		offline: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​a​ ​p​r​o​v​i​d​e​r
		 */
		configureProvider: string
		/**
		 * {​c​o​u​n​t​}​ ​m​e​s​s​a​g​e​s​ ​q​u​e​u​e​d
		 * @param {unknown} count
		 */
		messagesQueued: RequiredParams<'count'>
		/**
		 * R​e​t​r​y​ ​a​l​l
		 */
		retryQueue: string
		/**
		 * C​l​e​a​r​ ​q​u​e​u​e
		 */
		clearQueue: string
		/**
		 * D​i​s​c​a​r​d​ ​a​l​l​ ​q​u​e​u​e​d​ ​m​e​s​s​a​g​e​s​?
		 */
		clearQueueConfirm: string
	}
	modelCache: {
		/**
		 * A​l​l​ ​m​o​d​e​l​s​ ​r​e​f​r​e​s​h​e​d
		 */
		refreshed: string
		/**
		 * M​o​d​e​l​s​ ​c​a​c​h​e​d​ ​l​o​c​a​l​l​y​,​ ​r​e​f​r​e​s​h​e​d​ ​e​v​e​r​y​ ​2​4​ ​h​o​u​r​s
		 */
		cachedHint: string
		/**
		 * R​e​f​r​e​s​h​ ​A​l​l
		 */
		refreshAll: string
		/**
		 * N​o​ ​m​o​d​e​l​s​ ​l​o​a​d​e​d
		 */
		noModels: string
		/**
		 * {​c​o​u​n​t​}​ ​m​o​d​e​l​s
		 * @param {unknown} count
		 */
		modelsCount: RequiredParams<'count'>
		/**
		 * 2​4​h​ ​T​T​L
		 */
		ttl: string
		/**
		 * R​e​f​r​e​s​h
		 */
		refresh: string
	}
	dropZone: {
		/**
		 * D​r​o​p​ ​f​i​l​e​s​ ​t​o​ ​a​t​t​a​c​h
		 */
		dropFiles: string
		/**
		 * I​m​a​g​e​s​,​ ​t​e​x​t​,​ ​a​n​d​ ​c​o​d​e​ ​f​i​l​e​s​ ​(​m​a​x​ ​1​0​M​B​)
		 */
		hint: string
	}
	contextBar: {
		/**
		 * C​o​n​t​e​x​t​:
		 */
		label: string
		/**
		 * A​p​p​r​o​a​c​h​i​n​g​ ​l​i​m​i​t​ ​—​ ​o​l​d​e​r​ ​m​e​s​s​a​g​e​s​ ​m​a​y​ ​b​e​ ​t​r​i​m​m​e​d
		 */
		warning: string
		/**
		 * t​o​k​e​n​s​ ​u​s​e​d
		 */
		tokensUsed: string
	}
	exportFormats: {
		/**
		 * M​a​r​k​d​o​w​n​ ​(​.​m​d​)
		 */
		markdown: string
		/**
		 * J​S​O​N​ ​(​.​j​s​o​n​)
		 */
		json: string
		/**
		 * H​T​M​L​ ​(​.​h​t​m​l​)
		 */
		html: string
		/**
		 * P​l​a​i​n​ ​T​e​x​t​ ​(​.​t​x​t​)
		 */
		text: string
	}
	errorBoundary: {
		/**
		 * E​r​r​o​r​ ​i​n​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		errorInName: RequiredParams<'name'>
		/**
		 * U​n​k​n​o​w​n​ ​e​r​r​o​r
		 */
		unknownError: string
		/**
		 * T​r​y​ ​a​g​a​i​n
		 */
		tryAgain: string
		/**
		 * R​e​l​o​a​d​ ​p​a​g​e
		 */
		reloadPage: string
	}
	toast: {
		/**
		 * S​e​t​t​i​n​g​s​ ​s​a​v​e​d
		 */
		settingsSaved: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y
		 */
		copyFailed: string
		/**
		 * C​o​n​v​e​r​s​a​t​i​o​n​ ​e​x​p​o​r​t​e​d
		 */
		exportSuccess: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​e​x​p​o​r​t
		 */
		exportFailed: string
	}
	aria: {
		/**
		 * D​e​f​a​u​l​t​ ​p​r​o​v​i​d​e​r
		 */
		defaultProvider: string
		/**
		 * A​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
		 */
		availableModels: string
		/**
		 * R​e​g​e​n​e​r​a​t​e​ ​r​e​s​p​o​n​s​e
		 */
		regenerateResponse: string
		/**
		 * C​o​p​y​ ​m​e​s​s​a​g​e
		 */
		copyMessage: string
		/**
		 * M​o​r​e​ ​a​c​t​i​o​n​s
		 */
		moreActions: string
		/**
		 * T​o​g​g​l​e​ ​k​e​y​ ​v​i​s​i​b​i​l​i​t​y
		 */
		toggleKeyVisibility: string
		/**
		 * R​e​f​r​e​s​h​ ​m​o​d​e​l​s
		 */
		refreshModels: string
		/**
		 * A​r​c​h​i​v​e​ ​s​e​l​e​c​t​e​d
		 */
		archiveSelected: string
		/**
		 * D​e​l​e​t​e​ ​s​e​l​e​c​t​e​d
		 */
		deleteSelected: string
		/**
		 * C​a​n​c​e​l​ ​s​e​l​e​c​t​i​o​n
		 */
		cancelSelection: string
		/**
		 * S​e​l​e​c​t​ ​c​o​n​v​e​r​s​a​t​i​o​n​s
		 */
		selectConversations: string
		/**
		 * C​h​a​t​ ​m​e​s​s​a​g​e​s
		 */
		chatMessages: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * T​o​g​g​l​e​ ​t​h​e​m​e
		 */
		toggleTheme: string
		/**
		 * K​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s
		 */
		kbdShortcuts: string
		/**
		 * C​h​a​t​ ​i​n​p​u​t
		 */
		chatInput: string
		/**
		 * C​h​a​t​ ​m​e​s​s​a​g​e​ ​i​n​p​u​t
		 */
		chatMessageInput: string
		/**
		 * A​t​t​a​c​h​ ​f​i​l​e​s
		 */
		attachFiles: string
		/**
		 * S​t​o​p​ ​g​e​n​e​r​a​t​i​n​g
		 */
		stopGenerating: string
		/**
		 * S​e​n​d​ ​m​e​s​s​a​g​e
		 */
		sendMessage: string
		/**
		 * R​e​m​o​v​e​ ​f​i​l​e
		 */
		removeFile: string
		/**
		 * C​o​n​t​e​x​t​ ​w​i​n​d​o​w​ ​u​s​a​g​e
		 */
		contextWindowUsage: string
		/**
		 * R​e​t​r​y​ ​f​r​o​m​ ​s​c​r​a​t​c​h
		 */
		retryFromScratch: string
		/**
		 * U​s​e​r​ ​a​v​a​t​a​r
		 */
		userAvatar: string
		/**
		 * N​e​w​ ​c​h​a​t
		 */
		newChat: string
		/**
		 * S​k​i​l​l​s
		 */
		skills: string
	}
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​c​h​a​t​?
	 */
	deleteConfirmChat: string
	/**
	 * R​e​n​a​m​e​ ​c​h​a​t
	 */
	renameChatPrompt: string
	/**
	 * E​n​t​e​r​ ​w​o​r​k​s​p​a​c​e​ ​f​o​l​d​e​r​ ​p​a​t​h​:
	 */
	enterWorkspacePath: string
	/**
	 * V​i​e​w​ ​L​o​g​s
	 */
	viewLogs: string
	/**
	 * N​o​ ​a​r​c​h​i​v​e​d​ ​c​h​a​t​s
	 */
	noArchivedChats: string
	/**
	 * S​h​o​w​ ​a​r​c​h​i​v​e​d
	 */
	showArchived: string
	/**
	 * t​o​k​e​n​s
	 */
	streamingTokens: string
	/**
	 * C​l​i​c​k​ ​t​o​ ​r​e​c​o​r​d
	 */
	clickToRecord: string
	/**
	 * R​e​t​r​y​i​n​g​.​.​.
	 */
	retrying: string
	about: {
		/**
		 * B​u​i​l​t​ ​b​y​ ​M​o​r​t​e​n​ ​J​o​h​a​n​s​e​n
		 */
		builtBy: string
		/**
		 * A​G​P​L​-​3​.​0​ ​L​i​c​e​n​s​e
		 */
		license: string
	}
	updates: {
		/**
		 * U​p​d​a​t​e​ ​S​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
		 */
		autoCheck: string
		/**
		 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​d​o​w​n​l​o​a​d​ ​u​p​d​a​t​e​s
		 */
		autoDownload: string
		/**
		 * U​p​d​a​t​e​ ​c​h​a​n​n​e​l
		 */
		channel: string
		/**
		 * S​t​a​b​l​e
		 */
		stable: string
		/**
		 * B​e​t​a
		 */
		beta: string
		/**
		 * C​h​e​c​k​ ​N​o​w
		 */
		checkNow: string
		/**
		 * C​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
		 */
		checking: string
		/**
		 * U​p​d​a​t​e​ ​A​v​a​i​l​a​b​l​e
		 */
		available: string
		/**
		 * D​o​w​n​l​o​a​d​i​n​g​.​.​.
		 */
		downloading: string
		/**
		 * U​p​d​a​t​e​ ​r​e​a​d​y​ ​—​ ​r​e​s​t​a​r​t​ ​t​o​ ​i​n​s​t​a​l​l
		 */
		ready: string
		/**
		 * R​e​s​t​a​r​t​ ​N​o​w
		 */
		restartNow: string
		/**
		 * C​l​u​t​c​h​ ​i​s​ ​u​p​ ​t​o​ ​d​a​t​e
		 */
		upToDate: string
		/**
		 * L​a​s​t​ ​c​h​e​c​k​e​d
		 */
		lastChecked: string
		/**
		 * N​e​v​e​r
		 */
		never: string
	}
	slashCommands: {
		categories: {
			/**
			 * C​h​a​t
			 */
			chat: string
			/**
			 * W​o​r​k​s​p​a​c​e
			 */
			workspace: string
			/**
			 * W​e​b
			 */
			web: string
			/**
			 * S​k​i​l​l​s
			 */
			skills: string
			/**
			 * A​p​p
			 */
			app: string
		}
		descriptions: {
			/**
			 * S​w​i​t​c​h​ ​t​h​e​ ​a​c​t​i​v​e​ ​t​h​e​m​e
			 */
			switchTheme: string
			/**
			 * S​w​i​t​c​h​ ​t​h​e​ ​a​c​t​i​v​e​ ​m​o​d​e​l
			 */
			switchModel: string
			/**
			 * S​w​i​t​c​h​ ​t​h​e​ ​a​c​t​i​v​e​ ​p​r​o​v​i​d​e​r
			 */
			switchProvider: string
			/**
			 * S​h​o​w​ ​t​h​e​ ​a​c​t​i​v​e​ ​w​o​r​k​s​p​a​c​e​ ​p​a​t​h
			 */
			showWorkspace: string
			/**
			 * A​d​d​ ​a​ ​w​o​r​k​s​p​a​c​e​ ​d​i​r​e​c​t​o​r​y
			 */
			addWorkspace: string
			/**
			 * L​i​s​t​ ​i​n​s​t​a​l​l​e​d​ ​s​k​i​l​l​s
			 */
			listSkills: string
			/**
			 * R​e​a​d​ ​a​ ​f​i​l​e​ ​a​n​d​ ​i​n​j​e​c​t​ ​c​o​n​t​e​n​t​s​ ​i​n​t​o​ ​c​o​n​t​e​x​t
			 */
			readFile: string
			/**
			 * L​i​s​t​ ​f​i​l​e​s​ ​i​n​ ​w​o​r​k​s​p​a​c​e​ ​d​i​r​e​c​t​o​r​y
			 */
			listDir: string
			/**
			 * F​e​t​c​h​ ​w​e​b​p​a​g​e​ ​c​o​n​t​e​n​t​ ​a​s​ ​c​o​n​t​e​x​t
			 */
			fetchUrl: string
			/**
			 * F​e​t​c​h​ ​a​ ​G​i​t​H​u​b​ ​r​e​p​o​s​i​t​o​r​y​ ​R​E​A​D​M​E
			 */
			github: string
			/**
			 * L​o​a​d​ ​s​k​i​l​l​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​f​o​r​ ​t​h​i​s​ ​r​e​q​u​e​s​t
			 */
			loadSkill: string
			/**
			 * S​e​a​r​c​h​ ​c​u​r​a​t​e​d​ ​s​k​i​l​l​ ​c​a​t​a​l​o​g
			 */
			searchSkills: string
		}
		feedback: {
			/**
			 * T​h​e​m​e​ ​s​w​i​t​c​h​e​d​ ​t​o​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			themeSwitched: RequiredParams<'name'>
			/**
			 * A​c​t​i​v​e​ ​w​o​r​k​s​p​a​c​e​:​ ​{​p​a​t​h​}
			 * @param {unknown} path
			 */
			activeWorkspace: RequiredParams<'path'>
			/**
			 * N​o​ ​w​o​r​k​s​p​a​c​e​ ​a​c​t​i​v​e
			 */
			noWorkspace: string
			/**
			 * W​o​r​k​s​p​a​c​e​ ​a​d​d​e​d​:​ ​{​p​a​t​h​}
			 * @param {unknown} path
			 */
			workspaceAdded: RequiredParams<'path'>
		}
		errors: {
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​d​ ​w​o​r​k​s​p​a​c​e
			 */
			couldNotReadWorkspace: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​d​d​ ​w​o​r​k​s​p​a​c​e​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} error
			 */
			addWorkspaceFailed: RequiredParams<'error'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​a​d​ ​{​f​i​l​e​}​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} error
			 * @param {unknown} file
			 */
			readFileFailed: RequiredParams<'error' | 'file'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​l​i​s​t​ ​{​d​i​r​}​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} dir
			 * @param {unknown} error
			 */
			listDirFailed: RequiredParams<'dir' | 'error'>
		}
		aria: {
			/**
			 * C​o​m​m​a​n​d​ ​p​a​l​e​t​t​e
			 */
			commandPalette: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * Close
	 */
	close: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Next
	 */
	next: () => LocalizedString
	/**
	 * Done
	 */
	done: () => LocalizedString
	/**
	 * Search
	 */
	search: () => LocalizedString
	/**
	 * Loading...
	 */
	loading: () => LocalizedString
	/**
	 * Models Cache
	 */
	models: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * English
	 */
	english: () => LocalizedString
	/**
	 * Danish
	 */
	danish: () => LocalizedString
	/**
	 * German
	 */
	german: () => LocalizedString
	/**
	 * Polish
	 */
	polish: () => LocalizedString
	/**
	 * French
	 */
	french: () => LocalizedString
	/**
	 * Archive
	 */
	archive: () => LocalizedString
	/**
	 * Unarchive
	 */
	unarchive: () => LocalizedString
	/**
	 * Pin
	 */
	pin: () => LocalizedString
	/**
	 * Unpin
	 */
	unpin: () => LocalizedString
	/**
	 * Rename
	 */
	rename: () => LocalizedString
	/**
	 * Copy
	 */
	copy: () => LocalizedString
	/**
	 * Copied
	 */
	copied: () => LocalizedString
	/**
	 * Retry
	 */
	retry: () => LocalizedString
	/**
	 * Export
	 */
	'export': () => LocalizedString
	/**
	 * Install
	 */
	install: () => LocalizedString
	/**
	 * Uninstall
	 */
	uninstall: () => LocalizedString
	/**
	 * Enable
	 */
	enable: () => LocalizedString
	/**
	 * Disable
	 */
	disable: () => LocalizedString
	/**
	 * Test
	 */
	test: () => LocalizedString
	/**
	 * Refresh
	 */
	refresh: () => LocalizedString
	/**
	 * Clear
	 */
	clear: () => LocalizedString
	/**
	 * Confirm
	 */
	confirm: () => LocalizedString
	/**
	 * Dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * No results found.
	 */
	noResults: () => LocalizedString
	/**
	 * Something went wrong.
	 */
	somethingWentWrong: () => LocalizedString
	/**
	 * Reload
	 */
	reload: () => LocalizedString
	/**
	 * available
	 */
	balanceAvailable: () => LocalizedString
	/**
	 * unavailable
	 */
	balanceUnavailable: () => LocalizedString
	chat: {
		/**
		 * New Chat
		 */
		newChat: () => LocalizedString
		/**
		 * Send
		 */
		send: () => LocalizedString
		/**
		 * Type a message...
		 */
		typeMessage: () => LocalizedString
		/**
		 * Attach file
		 */
		attachFile: () => LocalizedString
		/**
		 * Regenerate
		 */
		regenerate: () => LocalizedString
		/**
		 * Stop generating
		 */
		stopGenerating: () => LocalizedString
		/**
		 * AI is responding...
		 */
		streaming: () => LocalizedString
		/**
		 * (edited)
		 */
		edited: () => LocalizedString
		/**
		 * This message was deleted.
		 */
		deleted: () => LocalizedString
		/**
		 * Delete this message?
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * No conversations yet.
		 */
		noSessions: () => LocalizedString
		/**
		 * Start a chat
		 */
		startChat: () => LocalizedString
		/**
		 * Today
		 */
		today: () => LocalizedString
		/**
		 * Yesterday
		 */
		yesterday: () => LocalizedString
		/**
		 * Older messages trimmed from context.
		 */
		olderMessagesTrimmed: () => LocalizedString
		/**
		 * Response interrupted
		 */
		responseInterrupted: () => LocalizedString
		/**
		 * Rate limited - retrying in {seconds}s
		 */
		rateLimited: (arg: { seconds: unknown }) => LocalizedString
		/**
		 * You
		 */
		you: () => LocalizedString
		/**
		 * Clutch
		 */
		assistant: () => LocalizedString
	}
	errors: {
		/**
		 * Network error. Check your connection.
		 */
		networkError: () => LocalizedString
		/**
		 * {provider} returned an error ({status}).
		 */
		apiError: (arg: { provider: unknown, status: unknown }) => LocalizedString
		/**
		 * Invalid API key for {provider}.
		 */
		invalidApiKey: (arg: { provider: unknown }) => LocalizedString
		/**
		 * Response stream was interrupted.
		 */
		streamInterrupted: () => LocalizedString
		/**
		 * An unknown error occurred.
		 */
		unknownError: () => LocalizedString
		/**
		 * {provider} is not configured. Add your API key in Settings.
		 */
		providerNotConfigured: (arg: { provider: unknown }) => LocalizedString
	}
	providers: {
		/**
		 * API Key
		 */
		apiKey: () => LocalizedString
		/**
		 * sk-...
		 */
		apiKeyPlaceholder: () => LocalizedString
		/**
		 * Default Model
		 */
		defaultModel: () => LocalizedString
		/**
		 * Test Connection
		 */
		testConnection: () => LocalizedString
		/**
		 * Connection successful
		 */
		connectionSuccess: () => LocalizedString
		/**
		 * Connection failed
		 */
		connectionFailed: () => LocalizedString
	}
	startup: {
		/**
		 * Launch on system startup
		 */
		startOnBoot: () => LocalizedString
		/**
		 * Start minimized to tray
		 */
		startMinimized: () => LocalizedString
		/**
		 * Close to tray instead of quitting
		 */
		closeToTray: () => LocalizedString
		/**
		 * Show icon in menu bar
		 */
		showTrayIcon: () => LocalizedString
		/**
		 * When disabled, the Clutch icon will not appear in the system menu bar. You can still access the app from the Dock or via keyboard shortcuts.
		 */
		showTrayIconDesc: () => LocalizedString
	}
	shortcuts: {
		/**
		 * Show Popup
		 */
		showPopup: () => LocalizedString
		/**
		 * Show Main
		 */
		showMain: () => LocalizedString
		/**
		 * Quick Ask
		 */
		quickAsk: () => LocalizedString
		/**
		 * {action} Shortcut
		 */
		shortcut: (arg: { action: unknown }) => LocalizedString
	}
	workspaces: {
		/**
		 * Workspaces
		 */
		title: () => LocalizedString
		/**
		 * Add Workspace
		 */
		add: () => LocalizedString
		/**
		 * Remove
		 */
		remove: () => LocalizedString
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * Workspaces give Clutch access to your project folders. The AI can read files, list directories, and run commands within the selected workspace. Add folders you want the assistant to work with.
		 */
		description: () => LocalizedString
		/**
		 * No workspaces added.
		 */
		noWorkspaces: () => LocalizedString
		/**
		 * Add a project folder to get started
		 */
		addCTA: () => LocalizedString
	}
	skills: {
		/**
		 * Verified GitHub repository
		 */
		verified: () => LocalizedString
		/**
		 * Skills
		 */
		title: () => LocalizedString
		/**
		 * Browse Skills
		 */
		browse: () => LocalizedString
		/**
		 * Installed
		 */
		installed: () => LocalizedString
		/**
		 * Search skills...
		 */
		searchSkills: () => LocalizedString
		/**
		 * No skills installed yet.
		 */
		noSkillsInstalled: () => LocalizedString
		/**
		 * Install
		 */
		installSkill: () => LocalizedString
		/**
		 * Uninstall
		 */
		uninstallSkill: () => LocalizedString
		/**
		 * Executing...
		 */
		executing: () => LocalizedString
		/**
		 * Skill details
		 */
		details: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
		/**
		 * Failed to install skill
		 */
		installFailed: () => LocalizedString
		/**
		 * Failed to uninstall skill
		 */
		uninstallFailed: () => LocalizedString
		/**
		 * Skill installed successfully
		 */
		installedSuccess: () => LocalizedString
		/**
		 * Skill uninstalled
		 */
		uninstalledSuccess: () => LocalizedString
		/**
		 * Uninstall "{name}"?
		 */
		uninstallConfirm: (arg: { name: unknown }) => LocalizedString
		/**
		 * Instructions
		 */
		instructions: () => LocalizedString
		/**
		 * No trending skills found
		 */
		noTrendingResults: () => LocalizedString
		/**
		 * Add a skill to get started
		 */
		addSkillsCTA: () => LocalizedString
		/**
		 * Curated Catalog
		 */
		curatedCatalog: () => LocalizedString
		/**
		 * Category
		 */
		category: () => LocalizedString
		/**
		 * Author
		 */
		author: () => LocalizedString
		/**
		 * Check for updates
		 */
		checkForUpdates: () => LocalizedString
		/**
		 * Checking...
		 */
		checking: () => LocalizedString
		/**
		 * Update available
		 */
		updateAvailable: () => LocalizedString
		/**
		 * All skills up to date
		 */
		upToDate: () => LocalizedString
		/**
		 * Update
		 */
		updateSkill: () => LocalizedString
		/**
		 * Updating...
		 */
		updating: () => LocalizedString
	}
	theme: {
		/**
		 * Theme
		 */
		theme: () => LocalizedString
		/**
		 * Theme Mode
		 */
		mode: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * System
		 */
		system: () => LocalizedString
		/**
		 * Time Format
		 */
		timeFormat: () => LocalizedString
		/**
		 * Auto
		 */
		auto: () => LocalizedString
		/**
		 * 12-hour
		 */
		hour12: () => LocalizedString
		/**
		 * 24-hour
		 */
		hour24: () => LocalizedString
	}
	exportSettings: {
		/**
		 * Default export format
		 */
		format: () => LocalizedString
		/**
		 * Include metadata
		 */
		includeMetadata: () => LocalizedString
		/**
		 * Include timestamps
		 */
		includeTimestamps: () => LocalizedString
		/**
		 * Include provider info
		 */
		includeProviderInfo: () => LocalizedString
	}
	profile: {
		/**
		 * Profile
		 */
		title: () => LocalizedString
		/**
		 * Display Name
		 */
		displayName: () => LocalizedString
		/**
		 * Set your display name
		 */
		setName: () => LocalizedString
		/**
		 * Avatar Type
		 */
		avatarType: () => LocalizedString
		/**
		 * Icon (default)
		 */
		iconDefault: () => LocalizedString
		/**
		 * Image
		 */
		image: () => LocalizedString
		/**
		 * Choose Image...
		 */
		chooseImage: () => LocalizedString
		/**
		 * Change Image
		 */
		changeImage: () => LocalizedString
		/**
		 * Avatar preview
		 */
		avatarPreview: () => LocalizedString
		/**
		 * Avatar Color
		 */
		avatarColor: () => LocalizedString
	}
	settingsTabs: {
		/**
		 * General
		 */
		general: () => LocalizedString
		/**
		 * Providers
		 */
		providers: () => LocalizedString
		/**
		 * Models
		 */
		models: () => LocalizedString
		/**
		 * Startup
		 */
		startup: () => LocalizedString
		/**
		 * Shortcuts
		 */
		shortcuts: () => LocalizedString
		/**
		 * Workspaces
		 */
		workspaces: () => LocalizedString
		/**
		 * Export
		 */
		'export': () => LocalizedString
		/**
		 * Skills
		 */
		skills: () => LocalizedString
		/**
		 * Updates
		 */
		updates: () => LocalizedString
	}
	settingsSections: {
		/**
		 * Appearance
		 */
		appearance: () => LocalizedString
		/**
		 * Locale
		 */
		locale: () => LocalizedString
		/**
		 * Time & Date
		 */
		timeDate: () => LocalizedString
		/**
		 * Permissions
		 */
		permissions: () => LocalizedString
		/**
		 * Developer
		 */
		developer: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * API Providers
		 */
		apiProviders: () => LocalizedString
		/**
		 * Startup Behavior
		 */
		startupBehavior: () => LocalizedString
		/**
		 * Keyboard Shortcuts
		 */
		keyboardShortcuts: () => LocalizedString
		/**
		 * Default Export Settings
		 */
		defaultExport: () => LocalizedString
		/**
		 * Show timestamps on messages
		 */
		showTimestamps: () => LocalizedString
		/**
		 * Developer mode
		 */
		developerMode: () => LocalizedString
		/**
		 * Enables right-click → Inspect Element for debugging
		 */
		developerHint: () => LocalizedString
		/**
		 * Updates
		 */
		updates: () => LocalizedString
	}
	permissions: {
		/**
		 * Allow file write commands · mkdir, touch, cp, mv, rm, ln, chmod, chown
		 */
		allowFileWrite: () => LocalizedString
		/**
		 * ⚠ Bypasses sandboxed write_file skill action
		 */
		allowFileWriteDesc: () => LocalizedString
		/**
		 * Allow network commands · curl, wget, nc, telnet, ssh
		 */
		allowNetwork: () => LocalizedString
		/**
		 * ⚠ Bypasses SSRF protections in web fetcher
		 */
		allowNetworkDesc: () => LocalizedString
		/**
		 * Allow process control · kill, killall, ps, top, systemctl
		 */
		allowProcess: () => LocalizedString
		/**
		 * ⚠ Can affect system processes
		 */
		allowProcessDesc: () => LocalizedString
	}
	shortcutActions: {
		/**
		 * New Chat
		 */
		newChat: () => LocalizedString
		/**
		 * Archive Chat
		 */
		archiveChat: () => LocalizedString
		/**
		 * Delete Chat
		 */
		deleteChat: () => LocalizedString
		/**
		 * Rename Chat
		 */
		renameChat: () => LocalizedString
		/**
		 * Pin/Unpin Chat
		 */
		pinUnpinChat: () => LocalizedString
		/**
		 * Copy Conversation
		 */
		copyConversation: () => LocalizedString
		/**
		 * Toggle Main Window
		 */
		toggleMainWindow: () => LocalizedString
	}
	welcome: {
		/**
		 * Clutch
		 */
		title: () => LocalizedString
		/**
		 * Grab the conversation
		 */
		tagline: () => LocalizedString
		/**
		 * Start a new chat to get started
		 */
		hint: () => LocalizedString
		/**
		 * Configure providers
		 */
		configureProviders: () => LocalizedString
	}
	networkStatus: {
		/**
		 * Message queued — will send when online
		 */
		messageQueued: () => LocalizedString
		/**
		 * Failed to send message after retries
		 */
		sendFailedAfterRetries: () => LocalizedString
		/**
		 * Connected
		 */
		connected: () => LocalizedString
		/**
		 * No API key
		 */
		noApiKey: () => LocalizedString
		/**
		 * Slow connection
		 */
		slowConnection: () => LocalizedString
		/**
		 * Offline
		 */
		offline: () => LocalizedString
		/**
		 * Configure a provider
		 */
		configureProvider: () => LocalizedString
		/**
		 * {count} messages queued
		 */
		messagesQueued: (arg: { count: unknown }) => LocalizedString
		/**
		 * Retry all
		 */
		retryQueue: () => LocalizedString
		/**
		 * Clear queue
		 */
		clearQueue: () => LocalizedString
		/**
		 * Discard all queued messages?
		 */
		clearQueueConfirm: () => LocalizedString
	}
	modelCache: {
		/**
		 * All models refreshed
		 */
		refreshed: () => LocalizedString
		/**
		 * Models cached locally, refreshed every 24 hours
		 */
		cachedHint: () => LocalizedString
		/**
		 * Refresh All
		 */
		refreshAll: () => LocalizedString
		/**
		 * No models loaded
		 */
		noModels: () => LocalizedString
		/**
		 * {count} models
		 */
		modelsCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * 24h TTL
		 */
		ttl: () => LocalizedString
		/**
		 * Refresh
		 */
		refresh: () => LocalizedString
	}
	dropZone: {
		/**
		 * Drop files to attach
		 */
		dropFiles: () => LocalizedString
		/**
		 * Images, text, and code files (max 10MB)
		 */
		hint: () => LocalizedString
	}
	contextBar: {
		/**
		 * Context:
		 */
		label: () => LocalizedString
		/**
		 * Approaching limit — older messages may be trimmed
		 */
		warning: () => LocalizedString
		/**
		 * tokens used
		 */
		tokensUsed: () => LocalizedString
	}
	exportFormats: {
		/**
		 * Markdown (.md)
		 */
		markdown: () => LocalizedString
		/**
		 * JSON (.json)
		 */
		json: () => LocalizedString
		/**
		 * HTML (.html)
		 */
		html: () => LocalizedString
		/**
		 * Plain Text (.txt)
		 */
		text: () => LocalizedString
	}
	errorBoundary: {
		/**
		 * Error in {name}
		 */
		errorInName: (arg: { name: unknown }) => LocalizedString
		/**
		 * Unknown error
		 */
		unknownError: () => LocalizedString
		/**
		 * Try again
		 */
		tryAgain: () => LocalizedString
		/**
		 * Reload page
		 */
		reloadPage: () => LocalizedString
	}
	toast: {
		/**
		 * Settings saved
		 */
		settingsSaved: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Failed to copy
		 */
		copyFailed: () => LocalizedString
		/**
		 * Conversation exported
		 */
		exportSuccess: () => LocalizedString
		/**
		 * Failed to export
		 */
		exportFailed: () => LocalizedString
	}
	aria: {
		/**
		 * Default provider
		 */
		defaultProvider: () => LocalizedString
		/**
		 * Available models
		 */
		availableModels: () => LocalizedString
		/**
		 * Regenerate response
		 */
		regenerateResponse: () => LocalizedString
		/**
		 * Copy message
		 */
		copyMessage: () => LocalizedString
		/**
		 * More actions
		 */
		moreActions: () => LocalizedString
		/**
		 * Toggle key visibility
		 */
		toggleKeyVisibility: () => LocalizedString
		/**
		 * Refresh models
		 */
		refreshModels: () => LocalizedString
		/**
		 * Archive selected
		 */
		archiveSelected: () => LocalizedString
		/**
		 * Delete selected
		 */
		deleteSelected: () => LocalizedString
		/**
		 * Cancel selection
		 */
		cancelSelection: () => LocalizedString
		/**
		 * Select conversations
		 */
		selectConversations: () => LocalizedString
		/**
		 * Chat messages
		 */
		chatMessages: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Toggle theme
		 */
		toggleTheme: () => LocalizedString
		/**
		 * Keyboard shortcuts
		 */
		kbdShortcuts: () => LocalizedString
		/**
		 * Chat input
		 */
		chatInput: () => LocalizedString
		/**
		 * Chat message input
		 */
		chatMessageInput: () => LocalizedString
		/**
		 * Attach files
		 */
		attachFiles: () => LocalizedString
		/**
		 * Stop generating
		 */
		stopGenerating: () => LocalizedString
		/**
		 * Send message
		 */
		sendMessage: () => LocalizedString
		/**
		 * Remove file
		 */
		removeFile: () => LocalizedString
		/**
		 * Context window usage
		 */
		contextWindowUsage: () => LocalizedString
		/**
		 * Retry from scratch
		 */
		retryFromScratch: () => LocalizedString
		/**
		 * User avatar
		 */
		userAvatar: () => LocalizedString
		/**
		 * New chat
		 */
		newChat: () => LocalizedString
		/**
		 * Skills
		 */
		skills: () => LocalizedString
	}
	/**
	 * Are you sure you want to delete this chat?
	 */
	deleteConfirmChat: () => LocalizedString
	/**
	 * Rename chat
	 */
	renameChatPrompt: () => LocalizedString
	/**
	 * Enter workspace folder path:
	 */
	enterWorkspacePath: () => LocalizedString
	/**
	 * View Logs
	 */
	viewLogs: () => LocalizedString
	/**
	 * No archived chats
	 */
	noArchivedChats: () => LocalizedString
	/**
	 * Show archived
	 */
	showArchived: () => LocalizedString
	/**
	 * tokens
	 */
	streamingTokens: () => LocalizedString
	/**
	 * Click to record
	 */
	clickToRecord: () => LocalizedString
	/**
	 * Retrying...
	 */
	retrying: () => LocalizedString
	about: {
		/**
		 * Built by Morten Johansen
		 */
		builtBy: () => LocalizedString
		/**
		 * AGPL-3.0 License
		 */
		license: () => LocalizedString
	}
	updates: {
		/**
		 * Update Settings
		 */
		title: () => LocalizedString
		/**
		 * Automatically check for updates
		 */
		autoCheck: () => LocalizedString
		/**
		 * Automatically download updates
		 */
		autoDownload: () => LocalizedString
		/**
		 * Update channel
		 */
		channel: () => LocalizedString
		/**
		 * Stable
		 */
		stable: () => LocalizedString
		/**
		 * Beta
		 */
		beta: () => LocalizedString
		/**
		 * Check Now
		 */
		checkNow: () => LocalizedString
		/**
		 * Checking for updates...
		 */
		checking: () => LocalizedString
		/**
		 * Update Available
		 */
		available: () => LocalizedString
		/**
		 * Downloading...
		 */
		downloading: () => LocalizedString
		/**
		 * Update ready — restart to install
		 */
		ready: () => LocalizedString
		/**
		 * Restart Now
		 */
		restartNow: () => LocalizedString
		/**
		 * Clutch is up to date
		 */
		upToDate: () => LocalizedString
		/**
		 * Last checked
		 */
		lastChecked: () => LocalizedString
		/**
		 * Never
		 */
		never: () => LocalizedString
	}
	slashCommands: {
		categories: {
			/**
			 * Chat
			 */
			chat: () => LocalizedString
			/**
			 * Workspace
			 */
			workspace: () => LocalizedString
			/**
			 * Web
			 */
			web: () => LocalizedString
			/**
			 * Skills
			 */
			skills: () => LocalizedString
			/**
			 * App
			 */
			app: () => LocalizedString
		}
		descriptions: {
			/**
			 * Switch the active theme
			 */
			switchTheme: () => LocalizedString
			/**
			 * Switch the active model
			 */
			switchModel: () => LocalizedString
			/**
			 * Switch the active provider
			 */
			switchProvider: () => LocalizedString
			/**
			 * Show the active workspace path
			 */
			showWorkspace: () => LocalizedString
			/**
			 * Add a workspace directory
			 */
			addWorkspace: () => LocalizedString
			/**
			 * List installed skills
			 */
			listSkills: () => LocalizedString
			/**
			 * Read a file and inject contents into context
			 */
			readFile: () => LocalizedString
			/**
			 * List files in workspace directory
			 */
			listDir: () => LocalizedString
			/**
			 * Fetch webpage content as context
			 */
			fetchUrl: () => LocalizedString
			/**
			 * Fetch a GitHub repository README
			 */
			github: () => LocalizedString
			/**
			 * Load skill instructions for this request
			 */
			loadSkill: () => LocalizedString
			/**
			 * Search curated skill catalog
			 */
			searchSkills: () => LocalizedString
		}
		feedback: {
			/**
			 * Theme switched to {name}
			 */
			themeSwitched: (arg: { name: unknown }) => LocalizedString
			/**
			 * Active workspace: {path}
			 */
			activeWorkspace: (arg: { path: unknown }) => LocalizedString
			/**
			 * No workspace active
			 */
			noWorkspace: () => LocalizedString
			/**
			 * Workspace added: {path}
			 */
			workspaceAdded: (arg: { path: unknown }) => LocalizedString
		}
		errors: {
			/**
			 * Could not read workspace
			 */
			couldNotReadWorkspace: () => LocalizedString
			/**
			 * Failed to add workspace: {error}
			 */
			addWorkspaceFailed: (arg: { error: unknown }) => LocalizedString
			/**
			 * Failed to read {file}: {error}
			 */
			readFileFailed: (arg: { error: unknown, file: unknown }) => LocalizedString
			/**
			 * Failed to list {dir}: {error}
			 */
			listDirFailed: (arg: { dir: unknown, error: unknown }) => LocalizedString
		}
		aria: {
			/**
			 * Command palette
			 */
			commandPalette: () => LocalizedString
		}
	}
}

export type Formatters = {}
