#!/bin/bash
set -e

FILE="src/lib/i18n/i18n-svelte.ts"

cat > "$FILE" << 'EOF'
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initI18nSvelte } from "typesafe-i18n/svelte";
import type {
  Formatters,
  Locales,
  TranslationFunctions,
  Translations,
} from "./i18n-types";
import { loadedFormatters, loadedLocales } from "./i18n-util";
import en from "./en/index";

const { locale, LL, setLocale } = initI18nSvelte<
  Locales,
  Translations,
  TranslationFunctions,
  Formatters
>(loadedLocales, loadedFormatters);

loadedLocales.en = en as unknown as Translations;
setLocale("en");

export { locale, LL, setLocale };

export default LL;
EOF

echo "✅ i18n-svelte.ts patched (default import + setLocale('en'))"
